[phases.setup]
nixPkgs = ['git', 'git-lfs']

[phases.install]
cmds = [
  'git lfs install',
  'git lfs pull'
]

[phases.build]
cmds = [
  'pip install -r requirements.txt'
]

[start]
cmd = 'uvicorn main:app --host 0.0.0.0 --port $PORT'

